# Generated by Django 3.2.6 on 2021-09-26 10:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='image/upload/wall2.jpg', max_length=255, verbose_name='images'),
        ),
    ]
